### ISSUE TITLE
Is your repo usable ?

### ISSUE THREAD

**Issue by sbernard31** [glhez/maven-repository#1]
I would like to try your [eclipse-settings-maven-plugin](https://github.com/glhez/eclipse-settings-maven-plugin) so I try to add you repo to my build but I can not success too make it works...

Any idea ?

The url given in the readme return `400: Invalid request` in my browser.

**Comment by glhez** [comment]
For your problem, I'm using a repository such as Nexus (https://fr.sonatype.com/download-oss-sonatype) so usually I don't see problem because the version is already loaded since long time ago. Nexus might "hide" some problem that Maven would have.

Github returns a 404 here https://raw.githubusercontent.com/glhez/maven-repository/master/releases and it is normal because they don't do directory listing. For files, this works: https://raw.githubusercontent.com/glhez/maven-repository/master/releases/com/github/glhez/eclipse-settings-maven-plugin/3.1.0/eclipse-settings-maven-plugin-3.1.0.pom

How are you consuming it ? Directly via Maven ?

While I appreciate you use my version of this maven plugin, you should probably clone this repository rather than explicitly depends on it (the reason being, I may clean it for whatever reason and it would break your build). 
Please take notice if you do clone this repo, the glhez in the URL must change.

**Comment by sbernard31** [comment]
@glhez Thx for your response and your responsiveness.

We currently use `maven-eclipse-plugin` for 2 purposes : 
1. transform maven project in eclipse one.
2. configure eclipse setting per projects.

But : 
1. is obsolete now as m2e is the right way to do.
2. for this part, I didn't find any good alternative.

About 2., `eclipse-settings-maven-plugin` sounds to almost do the job but I don't want to create a repos to store and share my setting I want it in the source code repository like with  `maven-eclipse-plugin`.  That's why I create this issue https://github.com/BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin/issues/8

But it seems that the project is pretty inactive, what is too bad... I see you open a PR with no more success than my issue ...
I also see that you fork the project and implement my feature request.

So first, I want to verify if this fits my needs, then I will see how to use it properly. Ideally I would like to get it from maven central but I read that you are not so motivate to release it this way.

> How are you consuming it ? Directly via Maven ?

Yep directly via Maven, I just add the repository but the artifact sounds never found.

**Comment by sbernard31** [comment]
Ok I finally succeed to use it by using <pluginRepositories> instead of <repositories>.
This looks like this : 
```xml
    <pluginRepositories>
        <pluginRepository>
            <id>github-maven-parent</id>
            <url>https://raw.github.com/glhez/maven-repository/master/releases/</url>
        </pluginRepository>
    </pluginRepositories>
```

And to run the goal : `mvn com.github.glhez:eclipse-settings-maven-plugin:eclipse-settings`

This works as needed but I faced 2 issues, I will open it on corresponding repository instead of here.

**Comment by glhez** [comment]
Okay. I'll close the issue then : it was only a configuration problem.
I fixed the README.md to point that.
